[package]
name = "pax-romana"
version = "0.1.0"
authors = ["tom barrett <spalf0@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.1"
rand = "0.7.0"
xml-rs = "0.8.0"
serde = { version = "1.0.98", features = ["derive"] }
serde_json = "1.0.40"

[profile.dev]
opt-level = 2
